name: Удаление пакета pdocker_package_test

# Управляет триггерами запуска workflow
on:

  # Запускает workflow при пушах или пул реквестах, но только для ветки master
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Позволяет запускать этот workflow вручную c вкладки CI/CD
  workflow_dispatch:

permissions:
  contents: read
  packages: write  

# Workflow состоит из одной или нескольких задач (job), выполняемых последовательно или параллельно
jobs:
  deleting_package_versions:

    name: Delete Package

    runs-on: ubuntu-latest

    steps:
      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'test_package_upload'
          package-type: 'npm'
          min-versions-to-keep: 2
          delete-only-pre-release-versions: false
          delete-only-untagged-versions: false
